/**
 * 加载资源文件
 * 作者：张春生
 * 日期：2012-12-04
 */
var worldmap_southEastAsia = "res/w/c/1/bg.png";
var characterName_bg = "res/ui/btn/bg.png";
var tmx_tiledwater = "res/w/t/water.png";
var tmx_tileddbwj1 = "res/w/o/dbwj1.png";
var tmx_tileddbwj2 = "res/w/o/dbwj2.png";
var tmx_tiledhouse1 = "res/w/o/house1.png";
var tmx_tiledhouse2 = "res/w/o/house2.png";
var tmx_tiledhouse3 = "res/w/o/house3.png";
var tmx_tiledhouse4 = "res/w/o/house4.png";
var tmx_tiledhouse5 = "res/w/o/house5.png";
var tmx_tiledland = "res/w/t/land.png";

var g_ressources = [{
		type: "image",
		src: worldmap_southEastAsia
	}, {
		type: "image",
		src: "res/jindutiao.png"
	}, {
		type: "image",
		src: "res/jindutiao_2.png"
	}, {
		type: "image",
		src: "res/jindutiao_3.png"
	}, {
		type: "image",
		src: "res/jindutiao_1.png"
	}, {
		type: "image",
		src: "res/noload.png"
	}, {
		type: "image",
		src: "res/c/loading.png"
	}, {
		type: "image",
		src: "res/font/shiqi.png"
	}, {
		type: "image",
		src: "res/font/add.png"
	}, {
		type: "image",
		src: "res/font/sub.png"
	}, {
		type: "image",
		src: "res/chuangkou/xuetiao2.png"
	}, {
		type: "image",
		src: "res/chuangkou/xuetiao1.png"
	}, {
		type: "image",
		src: "res/chuangkou/shiqi.png"
	}, {
		type: "image",
		src: characterName_bg
	}, {
		type: "image",
		src: tmx_tiledwater
	}, {
		type: "image",
		src: tmx_tileddbwj1
	}, {
		type: "image",
		src: tmx_tileddbwj2
	}, {
		type: "image",
		src: tmx_tiledhouse1
	}, {
		type: "image",
		src: tmx_tiledhouse2
	}, {
		type: "image",
		src: tmx_tiledhouse3
	}, {
		type: "image",
		src: tmx_tiledhouse4
	}, {
		type: "image",
		src: tmx_tiledhouse5
	}, {
		type: "image",
		src: tmx_tiledland
	},

	//plist
	{
		type: "plist",
		src: "res/c/0/0.plist"
	}, {
		type: "plist",
		src: "res/c/301/301.plist"
	}, {
		type: "plist",
		src: "res/c/302/302.plist"
	}, {
		type: "plist",
		src: "res/c/303/303.plist"
	}, {
		type: "plist",
		src: "res/c/304/304.plist"
	}, {
		type: "plist",
		src: "res/c/305/305.plist"
	}, {
		type: "plist",
		src: "res/c/306/306.plist"
	}, {
		type: "plist",
		src: "res/c/101/101.plist"
	}, {
		type: "plist",
		src: "res/c/102/102.plist"
	}, {
		type: "plist",
		src: "res/c/103/103.plist"
	}, {
		type: "plist",
		src: "res/c/107/107.plist"
	}, {
		type: "plist",
		src: "res/c/109/109.plist"
	}, {
		type: "plist",
		src: "res/c/110/110.plist"
	}, {
		type: "plist",
		src: "res/c/111/111.plist"
	}, {
		type: "plist",
		src: "res/c/112/112.plist"
	}, {
		type: "plist",
		src: "res/c/115/115.plist"
	}, {
		type: "plist",
		src: "res/c/6/6.plist"
	}, {
		type: "plist",
		src: "res/c/7/7.plist"
	}, {
		type: "plist",
		src: "res/c/8/8.plist"
	}, {
		type: "plist",
		src: "res/c/9/9.plist"
	}, {
		type: "plist",
		src: "res/c/10/10.plist"
	}, {
		type: "plist",
		src: "res/c/11/11.plist"
	}, {
		type: "plist",
		src: "res/c/12/12.plist"
	}, {
		type: "plist",
		src: "res/c/13/13.plist"
	}, {
		type: "plist",
		src: "res/c/14/14.plist"
	}, {
		type: "plist",
		src: "res/c/15/15.plist"
	}, {
		type: "plist",
		src: "res/c/16/16.plist"
	}, {
		type: "plist",
		src: "res/c/307/307.plist"
	}, {
		type: "plist",
		src: "res/c/308/308.plist"
	}, {
		type: "plist",
		src: "res/c/309/309.plist"
	}, {
		type: "plist",
		src: "res/c/310/310.plist"
	}, {
		type: "plist",
		src: "res/c/311/311.plist"
	}, {
		type: "plist",
		src: "res/c/312/312.plist"
	}, {
		type: "plist",
		src: "res/c/313/313.plist"
	}, {
		type: "plist",
		src: "res/c/314/314.plist"
	}, {
		type: "plist",
		src: "res/c/315/315.plist"
	}, {
		type: "plist",
		src: "res/c/316/316.plist"
	}, {
		type: "plist",
		src: "res/c/317/317.plist"
	}, {
		type: "plist",
		src: "res/c/318/318.plist"
	}, {
		type: "plist",
		src: "res/c/319/319.plist"
	}, {
		type: "plist",
		src: "res/c/320/320.plist"
	}, {
		type: "plist",
		src: "res/c/321/321.plist"
	}, {
		type: "plist",
		src: "res/c/322/322.plist"
	}, {
		type: "plist",
		src: "res/c/323/323.plist"
	}, {
		type: "plist",
		src: "res/c/324/324.plist"
	}, {
		type: "plist",
		src: "res/c/325/325.plist"
	}, {
		type: "plist",
		src: "res/c/326/326.plist"
	}
];