// Generated by CoffeeScript 1.3.3
(function () {
	var dataMgr, util;
	util = require("util");
	dataMgr = require("./xmlDataMgr").dataMgr;
	dataMgr.loadFiles();
	dataMgr.on("fileDone", function () {
		return process.exit(0);
	});
}).call(this);